name: 'Upload a Release Asset'
description: 'Upload a release asset to an existing release in your repository'
author: 'GitHub'
inputs:
  asset_path:
    description: 'The path to the asset you want to upload'
    required: true
  asset_name:
    description: 'The name of the asset you want to upload'
    required: true
  tag:
    description: 'Release tag name'
    required: true
outputs:
  browser_download_url:
    description: 'The URL users can navigate to in order to download the uploaded asset'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'gray-dark'
